### ISSUE TITLE
documentation link is not working 404

### ISSUE THREAD

**Issue by KushGoyal** [terra-money/terra-sdk-python#13]
please update the sdk docs link

**Comment by hanjukim** [comment]
@KushGoyal Is it fixed?

**Comment by KushGoyal** [comment]
No I am talking about this link: https://terra-project.github.io/terra-sdk-python/

This link is used everywhere in the Terra project docs and as the project url for this repo. But it is not working.

**Comment by hanjukim** [comment]
> No, not fixed yet. I am talking about this link: https://terra-project.github.io/terra-sdk-python/
> 
> This link is used everywhere in the Terra project docs and as the project url for this repo. But it is not working.

It has been moved to https://terra-money.github.io/terra-sdk-python

**Comment by Halimao** [comment]
> > No, not fixed yet. I am talking about this link: https://terra-project.github.io/terra-sdk-python/
> > This link is used everywhere in the Terra project docs and as the project url for this repo. But it is not working.
> 
> It has been moved to https://terra-money.github.io/terra-sdk-python Docs has been updated as well.

https://terra-money.github.io/terra-sdk-python is not working now, could u plz guide me to the new doc site, thanks very much
