### ISSUE TITLE
Fee estimator "fee_denoms" is no longer working on col-5 branch

### ISSUE THREAD

**Issue by unl1k3ly** [terra-money/terra-sdk-python#27]
Hi guys,

I'm testing col5 branch and it seems the way to simulate a fee against the node is no longer working. I'm just passing `fee_denoms=["uusd"]`  as normal and the following error returns:

`strconv.ParseFloat: parsing "['uusd']": invalid syntax` 
 
Thank you

**Comment by Vritra4** [comment]
thank you for telling us. fixed with 1.0.0b3.
